In [21]:
!pip3 install pandas
!pip3 install openpyxl

Requirement already satisfied: pandas in /Users/sborda/opt/anaconda3/lib/python3.8/site-packages (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/sborda/opt/anaconda3/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /Users/sborda/opt/anaconda3/lib/python3.8/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/sborda/opt/anaconda3/lib/python3.8/site-packages (from pandas) (1.20.1)
Requirement already satisfied: six>=1.5 in /Users/sborda/opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: openpyxl in /Users/sborda/opt/anaconda3/lib/python3.8/site-packages (3.0.7)
Requirement already satisfied: et-xmlfile in /Users/sborda/opt/anaconda3/lib/python3.8/site-packages (from openpyxl) (1.0.1)

In [22]:
import pandas as pd
url = 'https://www.fulcrum.org/downloads/b8515n388?locale=en'
#path = ('...\\filename.xlsx')
xl = pd.ExcelFile(url)
print(xl.sheet_names)
shName = xl.sheet_names

['Table 9']

In [23]:
df = pd.read_excel(url, shName[0])
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', 500)
display(df)

/Users/sborda/opt/anaconda3/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Phase 2,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,ELEMENT,SUS DOMESTICUS,NaN,NaN,OVIS VEL CAPRA,NaN,NaN,BOS TAURUS,NaN,NaN
1,NaN,NR,NME,NMI,NR,NME,NMI,NR,NME,NMI
2,Horn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cranium 1/2,13,3,3,NaN,NaN,NaN,10,4,3
4,Maxilla 1/2,2,2,2,2,2,2,3,3,2
5,Mandible 1/2,12,6,5,1,1,1,8,3,2
6,Teeth,19,14,7,8,8,7,7,7,3
7,Hyoid,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN
8,Atlas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Axis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Cerv.Vert.,NaN,NaN,NaN,2,2,2,5,3,3
11,Tor.Vert.,NaN,NaN,NaN,4,2,2,7,4,3
12,Lumb.Vert.,NaN,NaN,NaN,8,4,4,NaN,NaN,NaN
13,Sacr.Vert.,NaN,NaN,NaN,NaN,NaN,NaN,2,1,1
14,Caud. Vert.,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN
15,Vertebra,NaN,NaN,NaN,1,1,1,3,1,1
16,Rib,15,9,4,52,12,6,4,1,1
17,Scapula,3,2,2,3,3,3,3,3,3
18,Humerus,3,3,3,5,4,3,3,3,2
19,Radius,11,9,6,2,2,2,NaN,NaN,NaN
20,Ulna,3,3,3,1,1,1,3,3,3
21,Pelvis 1/2,6,5,4,5,3,3,5,2,1
22,Femur,4,4,4,1,1,1,NaN,NaN,NaN
23,Patella,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Tibia,2,1,1,2,2,2,2,1,1
25,Malleolus/Fibula,4,2,1,NaN,NaN,NaN,NaN,NaN,NaN
26,Carpals,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN
27,Astragalus,3,3,2,1,1,1,NaN,NaN,NaN
28,Calcaneum,2,2,2,1,1,1,NaN,NaN,NaN
29,Tarsals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Metacarpals,6,6,4,2,2,2,NaN,NaN,NaN
31,Metatarsals,5,5,1,3,3,3,1,1,1
32,Metapodials,9,8,3,NaN,NaN,NaN,1,1,1
33,Phalanx 1,3,3,2,1,1,1,NaN,NaN,NaN
34,Phalanx 2,2,2,2,NaN,NaN,NaN,1,1,1
35,Phalanx 3,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN
36,Sesamoids,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Total,129,94,NaN,108,59,NaN,68,42,NaN